spring:
  datasource:
      url: jdbc:mysql://localhost:3306/jpa_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
        use_sql_comments: true
        highlight_sql: true
  output:
    ansi:
      enabled: always

logging.level.org.hibernate.orm.jdbc.bind: trace
