spring:
  datasource:
      url: jdbc:mysql://localhost:3306/jpa_shop?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true